-- EMBRIOGESTOR 2.0 - NUVEM PRINCIPAL SUPABASE
-- Execute este arquivo no Supabase > SQL Editor > New query > Run

create table if not exists public.embrio_app_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  revision bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.embrio_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payload jsonb not null,
  source text not null default 'AUTO',
  created_at timestamptz not null default now()
);

create index if not exists idx_embrio_backups_user_created
  on public.embrio_backups(user_id, created_at desc);

alter table public.embrio_app_state enable row level security;
alter table public.embrio_backups enable row level security;

drop policy if exists "embrio_state_select_own" on public.embrio_app_state;
drop policy if exists "embrio_state_insert_own" on public.embrio_app_state;
drop policy if exists "embrio_state_update_own" on public.embrio_app_state;
drop policy if exists "embrio_backups_select_own" on public.embrio_backups;
drop policy if exists "embrio_backups_insert_own" on public.embrio_backups;
drop policy if exists "embrio_backups_delete_own" on public.embrio_backups;

create policy "embrio_state_select_own"
on public.embrio_app_state for select
to authenticated
using (auth.uid() = user_id);

create policy "embrio_state_insert_own"
on public.embrio_app_state for insert
to authenticated
with check (auth.uid() = user_id);

create policy "embrio_state_update_own"
on public.embrio_app_state for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "embrio_backups_select_own"
on public.embrio_backups for select
to authenticated
using (auth.uid() = user_id);

create policy "embrio_backups_insert_own"
on public.embrio_backups for insert
to authenticated
with check (auth.uid() = user_id);

create policy "embrio_backups_delete_own"
on public.embrio_backups for delete
to authenticated
using (auth.uid() = user_id);

-- Opcional: manter apenas os 60 backups mais recentes por usuário pode ser feito
-- mais tarde por função agendada. Nesta fase nenhum backup é apagado automaticamente.
