import { useMemo, useState } from 'react'
import type { BancoEmbrioGestor, EstoqueEmbriaoItem, MovimentacaoItem } from '../types/domain'
import { Field, Modal, SearchBar, SearchableSelect } from '../components/CrudUI'
import { handleEnterFlow } from '../components/EnterFlow'
import { touroDoCliente } from '../services/tourosClientes'
const id=(p:string)=>p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,6)
const n=(v:any)=>Math.max(0,Number(v)||0)
const norm=(v:any)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const vazio:EstoqueEmbriaoItem={id:'',clienteId:'',data:new Date().toISOString().slice(0,10),doadoraId:'',touroId:'',tipo:'DT',quantidade:0,botijao:'',caneca:'',raque:'',posicao:'',obs:''}

export function EstoqueEmbrioes({db,onChange}:{db:BancoEmbrioGestor,onChange:(db:BancoEmbrioGestor)=>void}){
 const[busca,setBusca]=useState('');const[edit,setEdit]=useState<EstoqueEmbriaoItem|null>(null);const[clienteAberto,setClienteAberto]=useState<string|null>(null);const[dataAberta,setDataAberta]=useState<string|null>(null)
 const grupos=useMemo(()=>db.clientes.map(c=>{const itens=db.estoqueEmbrioes.filter(e=>e.clienteId===c.id).filter(e=>{const d=db.doadoras.find(x=>x.id===e.doadoraId);const t=db.touros.find(x=>x.id===e.touroId);return !busca||norm([c.nome,c.propriedade,c.municipio,d?.nome,d?.registro,t?.nome,e.tipo,e.botijao,e.caneca,e.raque,e.posicao].join(' ')).includes(norm(busca))});return {cliente:c,itens,total:db.estoqueEmbrioes.filter(e=>e.clienteId===c.id).reduce((s,e)=>s+n(e.quantidade),0)}}).filter(g=>busca?g.itens.length:true).sort((a,b)=>a.cliente.nome.localeCompare(b.cliente.nome,'pt-BR')),[db,busca])
 function salvar(e:EstoqueEmbriaoItem){if(!e.clienteId||!e.doadoraId||!e.touroId)return alert('Informe cliente, doadora e touro.');const existente=e.id?db.estoqueEmbrioes.find(x=>x.id===e.id):undefined;const item={...e,id:e.id||id('EMBEST'),quantidade:n(e.quantidade)};const estoqueEmbrioes=e.id?db.estoqueEmbrioes.map(x=>x.id===e.id?item:x):[...db.estoqueEmbrioes,item];const delta=existente?n(item.quantidade)-n(existente.quantidade):n(item.quantidade);let movimentacoes=db.movimentacoes;if(delta!==0){const mov:MovimentacaoItem={id:id('MOV'),data:new Date().toISOString(),tipo:delta>0?'ENTRADA_EMBRIAO':'AJUSTE',clienteId:item.clienteId,doadoraId:item.doadoraId,touroId:item.touroId,estoqueId:item.id,quantidade:Math.abs(delta),descricao:delta>0?'Entrada de embriões no estoque':'Ajuste manual de estoque de embriões'};movimentacoes=[...movimentacoes,mov]}onChange({...db,estoqueEmbrioes,movimentacoes});setEdit(null)}
 const doadorasCliente=edit?db.doadoras.filter(d=>d.clienteId===edit.clienteId):[];const tourosCliente=edit?db.touros.filter(t=>touroDoCliente(t,edit.clienteId)):[]
 return <section className="panel embryo-stock-compact"><div className="panel-head"><div><h2>Estoque de Embriões</h2><p>Embriões DT e VT organizados por cliente.</p></div></div>
 <div className="toolbar"><SearchBar value={busca} onChange={setBusca} placeholder="Localizar cliente, doadora, touro, DT/VT ou localização"/></div>
 <div className={`embryo-client-grid ${clienteAberto&&!busca?'has-open':''}`}>{grupos.map(g=>{const aberto=clienteAberto===g.cliente.id;if(clienteAberto&&!aberto)return null;return <div className={`embryo-client-card ${aberto?'is-open':''}`} key={g.cliente.id}>
 <button className="embryo-client-button" onClick={()=>{setClienteAberto(aberto?null:g.cliente.id);setDataAberta(null);if(!aberto)setBusca('')}}><span className="embryo-folder-icon">▰</span><span className="embryo-client-main"><strong>{g.cliente.nome}</strong><small>{g.cliente.propriedade||g.cliente.municipio||'Cliente'}</small></span><span className="embryo-count">{g.total} embrião(ões)</span></button>
 {aberto&&<div className="embryo-open-content"><div className="embryo-open-head"><div><strong>{g.cliente.nome}</strong><span>{g.total} embrião(ões) em estoque</span></div><div className="actions"><button className="btn small" onClick={()=>{setClienteAberto(null);setDataAberta(null);setBusca('')}}>Voltar aos clientes</button><button className="btn primary small" onClick={()=>setEdit({...vazio,clienteId:g.cliente.id})}>+ Nova entrada</button></div></div>
 {g.itens.length?<div className="date-folder-grid">{[...new Set(g.itens.map(e=>String(e.data||'').slice(0,10)))].sort((a,b)=>b.localeCompare(a)).map(data=>{const itensData=g.itens.filter(e=>String(e.data||'').slice(0,10)===data);const chave=g.cliente.id+'|'+data;const aberta=dataAberta===chave;return <div className={`date-folder-card ${aberta?'is-open':''}`} key={chave}><button className="date-folder-button" onClick={()=>setDataAberta(aberta?null:chave)}><span className="date-folder-icon">▰</span><span><strong>{data?data.split('-').reverse().join('/'):'Sem data'}</strong><small>{itensData.reduce((a,e)=>a+n(e.quantidade),0)} embrião(ões)</small></span></button>{aberta&&<div className="date-folder-content"><div className="date-folder-head"><strong>Congelamentos de {data?data.split('-').reverse().join('/'):'data não informada'}</strong><button className="btn small" onClick={()=>setDataAberta(null)}>Fechar data</button></div><div className="table-wrap"><table><thead><tr><th>Doadora</th><th>Touro</th><th>Tipo</th><th>Qtd.</th><th>Botijão</th><th>Caneca</th><th>Raque</th><th>Posição</th><th>Ações</th></tr></thead><tbody>{itensData.map(e=>{const d=db.doadoras.find(x=>x.id===e.doadoraId);const t=db.touros.find(x=>x.id===e.touroId);return <tr key={e.id}><td><strong>{d?.nome||'—'}</strong></td><td>{t?.nome||'—'}</td><td><strong>{e.tipo}</strong></td><td>{e.quantidade}</td><td>{e.botijao||'—'}</td><td>{e.caneca||'—'}</td><td>{e.raque||'—'}</td><td>{e.posicao||'—'}</td><td><div className="actions"><button className="btn small" onClick={()=>setEdit({...e})}>Editar</button><button className="btn small danger" onClick={()=>{if(confirm('Excluir este item?'))onChange({...db,estoqueEmbrioes:db.estoqueEmbrioes.filter(x=>x.id!==e.id)})}}>Excluir</button></div></td></tr>})}</tbody></table></div></div>}</div>})}</div>:<div className="note-box">Nenhum embrião em estoque para este cliente.</div>}</div>}</div>})}</div>
 {edit&&<Modal title={edit.id?'Editar estoque de embriões':'Nova entrada de embriões'} onClose={()=>setEdit(null)}><div className="form-grid" onKeyDown={handleEnterFlow}>
 <Field label="Data"><input type="date" value={edit.data||''} onChange={e=>setEdit({...edit,data:e.target.value})}/></Field>
 <Field label="Cliente"><SearchableSelect value={edit.clienteId} onChange={v=>setEdit({...edit,clienteId:v,doadoraId:'',touroId:''})} options={db.clientes.map(c=>({value:c.id,label:c.nome,search:[c.propriedade,c.municipio,c.cpf].join(' ')}))} placeholder="Digite o nome do cliente"/></Field>
 <Field label="Doadora"><SearchableSelect value={edit.doadoraId} onChange={v=>setEdit({...edit,doadoraId:v})} options={doadorasCliente.map(d=>({value:d.id,label:d.nome,search:[d.registro,d.raca,d.categoria].join(' ')}))} placeholder="Digite o número/nome da doadora"/></Field>
 <Field label="Touro"><SearchableSelect value={edit.touroId} onChange={v=>setEdit({...edit,touroId:v})} options={tourosCliente.map(t=>({value:t.id,label:t.nome,search:[t.registro,t.codigo,t.raca].join(' ')}))} placeholder="Digite o nome do touro"/></Field>
 <Field label="Tipo"><select value={edit.tipo} onChange={e=>setEdit({...edit,tipo:e.target.value as any})}><option value="DT">DT</option><option value="VT">VT</option></select></Field>
 <Field label="Quantidade"><input type="number" min="0" value={edit.quantidade} onChange={e=>setEdit({...edit,quantidade:n(e.target.value)})}/></Field>
 <Field label="Botijão"><input value={edit.botijao||''} onChange={e=>setEdit({...edit,botijao:e.target.value})}/></Field><Field label="Caneca"><input value={edit.caneca||''} onChange={e=>setEdit({...edit,caneca:e.target.value})}/></Field><Field label="Raque"><input value={edit.raque||''} onChange={e=>setEdit({...edit,raque:e.target.value})}/></Field><Field label="Posição"><input value={edit.posicao||''} onChange={e=>setEdit({...edit,posicao:e.target.value})}/></Field><Field label="Observações"><input value={edit.obs||''} onChange={e=>setEdit({...edit,obs:e.target.value})}/></Field>
 </div><div className="modal-actions"><button className="btn" onClick={()=>setEdit(null)}>Cancelar</button><button className="btn primary" data-enter-final="true" onClick={()=>salvar(edit)}>Salvar estoque</button></div></Modal>}</section>
}
